// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.tajinsurance.domain;

import java.util.Date;

privileged aspect Contract_Roo_JavaBean {


}
